name 'justinclayton-nexus'
version '1.0.0'
source 'https://github.com/justinclayton/puppet-module-nexus.git'
author 'justinclayton'
license 'MIT'
summary 'Puppet module for nexus'
description 'Puppet module for nexus'
project_page 'https://github.com/justinclayton/puppet-module-nexus'

dependency 'puppetlabs/java', '>= 1.0.1'
dependency 'nanliu/staging',  '>= 0.3.1'
